mod build_provenance;
#[allow(dead_code)]
#[path = "benchmark/sha256.rs"]
mod sha256;

use std::env;
use std::fmt::Write as _;
use std::fs;
#[cfg(unix)]
use std::io::Read as _;
use std::path::Path;
use std::process::Command;

use build_provenance::{
    cargo_vcs_provenance, has_hidden_git_index_entries, owned_git_repository, parse_dirty,
};

const BUILD_CONFIGURATION_REQUIRED_ENV_KEYS: &[&str] =
    &["PROFILE", "OPT_LEVEL", "DEBUG", "TARGET", "HOST", "OUT_DIR"];
const BUILD_CONFIGURATION_OPTIONAL_ENV_KEYS: &[&str] = &[
    "CARGO_ENCODED_RUSTFLAGS",
    "CARGO_INCREMENTAL",
    "RUSTFLAGS",
    "RUSTC_WRAPPER",
    "RUSTC_WORKSPACE_WRAPPER",
];
const BUILD_AUTHORIZATION_ENV: &str = "RUSTHOUSE_ATTESTED_BUILD_AUTHORIZATION";

struct SourceProvenance {
    commit: String,
    dirty: bool,
    git_watch_paths: Vec<std::path::PathBuf>,
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is required");
    let manifest_dir = Path::new(&manifest_dir);

    let source = source_provenance(manifest_dir);
    if !matches!(source.commit.len(), 40 | 64)
        || !source
            .commit
            .chars()
            .all(|character| character.is_ascii_hexdigit())
    {
        panic!(
            "source provenance contains an invalid commit: {:?}",
            source.commit
        );
    }

    let rustc = env::var("RUSTC").expect("RUSTC is required");
    let rustc_version = command_output(manifest_dir, &rustc, &["--version"]);
    let target = required_env("TARGET");
    let profile = required_env("PROFILE");
    let build_configuration_seed_sha256 = build_configuration_seed_sha256();

    emit(
        "RUSTHOUSE_SOURCE_COMMIT",
        &source.commit.to_ascii_lowercase(),
    );
    emit(
        "RUSTHOUSE_SOURCE_DIRTY",
        if source.dirty { "true" } else { "false" },
    );
    emit("RUSTHOUSE_RUSTC_VERSION", &rustc_version);
    emit("RUSTHOUSE_BUILD_TARGET", &target);
    emit("RUSTHOUSE_BUILD_PROFILE", &profile);
    emit(
        "RUSTHOUSE_ATTESTED_BUILD_TOKEN",
        &attested_build_token(manifest_dir),
    );
    emit(
        "RUSTHOUSE_BUILD_CONFIGURATION_SHA256",
        &build_configuration_seed_sha256,
    );

    println!("cargo:rerun-if-env-changed=RUSTC");
    println!("cargo:rerun-if-env-changed=RUSTHOUSE_ATTESTED_BUILD");
    println!("cargo:rerun-if-env-changed=RUSTHOUSE_ATTESTED_BUILD_SESSION");
    println!("cargo:rerun-if-env-changed={BUILD_AUTHORIZATION_ENV}");
    println!("cargo:rerun-if-env-changed=RUSTHOUSE_ATTESTED_BUILD_TOKEN");
    println!("cargo:rerun-if-env-changed=RUSTHOUSE_BUILD_SOURCE_COMMIT");
    println!("cargo:rerun-if-env-changed=RUSTHOUSE_BUILD_SOURCE_DIRTY");
    emit_build_configuration_env_watches();
    emit_source_watches(manifest_dir);
    for path in source.git_watch_paths {
        println!("cargo:rerun-if-changed={}", path.display());
    }
}

fn attested_build_token(manifest_dir: &Path) -> String {
    if env::var_os("RUSTHOUSE_ATTESTED_BUILD_TOKEN").is_some() {
        panic!(
            "RUSTHOUSE_ATTESTED_BUILD_TOKEN is generated by build.rs and must not be supplied by the caller"
        );
    }
    match env::var("RUSTHOUSE_ATTESTED_BUILD").ok().as_deref() {
        None => "unavailable".to_owned(),
        Some("1") => {
            validate_build_authorization(manifest_dir);
            fresh_attestation_token()
        }
        Some(value) => {
            panic!("RUSTHOUSE_ATTESTED_BUILD must be 1, got {value:?}")
        }
    }
}

fn validate_build_authorization(manifest_dir: &Path) {
    let authorization_path = env::var(BUILD_AUTHORIZATION_ENV)
        .unwrap_or_else(|_| panic!("attested build authorization is unavailable"));
    let authorization_path = Path::new(&authorization_path);
    let metadata = fs::metadata(authorization_path).unwrap_or_else(|error| {
        panic!(
            "could not inspect attested build authorization '{}': {error}",
            authorization_path.display()
        )
    });
    if !metadata.is_file() {
        panic!("attested build authorization is not a regular file");
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt as _;
        if metadata.permissions().mode() & 0o077 != 0 {
            panic!("attested build authorization is accessible by other users");
        }
    }
    let contents = fs::read_to_string(authorization_path)
        .unwrap_or_else(|error| panic!("could not read attested build authorization: {error}"));
    let session = required_authorization_field(&contents, "session");
    let expected_session = env::var("RUSTHOUSE_ATTESTED_BUILD_SESSION")
        .unwrap_or_else(|_| panic!("attested build session is unavailable"));
    if session != expected_session {
        panic!("attested build authorization has the wrong session");
    }
    let expected_wrapper_sha256 = required_authorization_field(&contents, "wrapper_sha256");
    let wrapper = env::var("RUSTC_WORKSPACE_WRAPPER")
        .unwrap_or_else(|_| panic!("attested workspace wrapper is unavailable"));
    let actual_wrapper_sha256 = sha256::file_digest_hex(Path::new(&wrapper))
        .unwrap_or_else(|error| panic!("could not hash attested workspace wrapper: {error}"));
    if actual_wrapper_sha256 != expected_wrapper_sha256 {
        panic!("attested workspace wrapper does not match builder authorization");
    }
    let authorization_parent = authorization_path
        .parent()
        .and_then(|path| fs::canonicalize(path).ok())
        .unwrap_or_else(|| panic!("attested build authorization has no resolved parent"));
    let source_parent = manifest_dir
        .parent()
        .and_then(|path| fs::canonicalize(path).ok())
        .unwrap_or_else(|| panic!("attested source snapshot has no resolved parent"));
    if authorization_parent != source_parent {
        panic!("attested build authorization is outside the private source snapshot");
    }
}

fn required_authorization_field(contents: &str, name: &str) -> String {
    let prefix = format!("{name}=");
    contents
        .lines()
        .find_map(|line| line.strip_prefix(&prefix))
        .filter(|value| !value.is_empty())
        .unwrap_or_else(|| panic!("attested build authorization omitted {name}"))
        .to_owned()
}

fn fresh_attestation_token() -> String {
    let mut bytes = [0_u8; 32];
    fill_random(&mut bytes);
    let mut token = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        write!(token, "{byte:02x}").expect("writing to String cannot fail");
    }
    token
}

#[cfg(unix)]
fn fill_random(bytes: &mut [u8]) {
    fs::File::open("/dev/urandom")
        .and_then(|mut random| random.read_exact(bytes))
        .unwrap_or_else(|error| panic!("could not obtain an attested-build challenge: {error}"));
}

#[cfg(windows)]
fn fill_random(bytes: &mut [u8]) {
    use std::ffi::c_void;

    #[link(name = "bcrypt")]
    unsafe extern "system" {
        fn BCryptGenRandom(algorithm: *mut c_void, buffer: *mut u8, length: u32, flags: u32)
        -> i32;
    }
    const USE_SYSTEM_PREFERRED_RNG: u32 = 0x0000_0002;
    let length = u32::try_from(bytes.len()).expect("random request length fits u32");
    // A null algorithm handle with this flag selects Windows' system RNG.
    let status = unsafe {
        BCryptGenRandom(
            std::ptr::null_mut(),
            bytes.as_mut_ptr(),
            length,
            USE_SYSTEM_PREFERRED_RNG,
        )
    };
    if status < 0 {
        panic!("could not obtain an attested-build challenge: BCryptGenRandom status {status:#x}");
    }
}

#[cfg(not(any(unix, windows)))]
fn fill_random(_bytes: &mut [u8]) {
    panic!("attested release builds require an operating-system random source")
}

fn source_provenance(manifest_dir: &Path) -> SourceProvenance {
    if let Some(repository) = owned_git_repository(manifest_dir) {
        let status = command_output(
            manifest_dir,
            "git",
            &[
                "--no-optional-locks",
                "status",
                "--porcelain=v1",
                "--untracked-files=normal",
            ],
        );
        let hidden_index_entries = has_hidden_git_index_entries(manifest_dir)
            .unwrap_or_else(|| panic!("could not inspect Git index flags"));
        return SourceProvenance {
            commit: repository.commit,
            dirty: !status.is_empty() || hidden_index_entries,
            git_watch_paths: repository.watch_paths,
        };
    }

    let vcs_path = manifest_dir.join(".cargo_vcs_info.json");
    if vcs_path.is_file() {
        let contents = fs::read_to_string(&vcs_path).unwrap_or_else(|error| {
            panic!(
                "could not read packaged VCS metadata '{}': {error}",
                vcs_path.display()
            )
        });
        let provenance = cargo_vcs_provenance(&contents).unwrap_or_else(|| {
            panic!(
                "packaged VCS metadata '{}' does not contain valid git.sha1/dirty fields",
                vcs_path.display()
            )
        });
        return SourceProvenance {
            commit: provenance.commit,
            dirty: true,
            git_watch_paths: Vec::new(),
        };
    }

    let explicit_commit = env::var("RUSTHOUSE_BUILD_SOURCE_COMMIT").ok();
    let explicit_dirty = env::var("RUSTHOUSE_BUILD_SOURCE_DIRTY").ok();
    match (explicit_commit, explicit_dirty) {
        (Some(commit), Some(dirty)) => {
            let _declared_dirty = parse_dirty(&dirty).unwrap_or_else(|| {
                panic!("RUSTHOUSE_BUILD_SOURCE_DIRTY must be true or false, got {dirty:?}")
            });
            return SourceProvenance {
                commit,
                dirty: true,
                git_watch_paths: Vec::new(),
            };
        }
        (Some(_), None) | (None, Some(_)) => {
            panic!(
                "RUSTHOUSE_BUILD_SOURCE_COMMIT and RUSTHOUSE_BUILD_SOURCE_DIRTY must be supplied together"
            );
        }
        (None, None) => {}
    }

    panic!(
        "source provenance is unavailable: no package-owned Git checkout, packaged .cargo_vcs_info.json, or explicit RUSTHOUSE_BUILD_SOURCE_COMMIT/RUSTHOUSE_BUILD_SOURCE_DIRTY inputs"
    );
}

fn build_configuration_seed_sha256() -> String {
    let mut settings = vec![
        ("PROFILE".to_owned(), required_env("PROFILE")),
        ("OPT_LEVEL".to_owned(), required_env("OPT_LEVEL")),
        ("DEBUG".to_owned(), required_env("DEBUG")),
        ("TARGET".to_owned(), required_env("TARGET")),
        ("HOST".to_owned(), required_env("HOST")),
        (
            "CARGO_UNIT_FINGERPRINT".to_owned(),
            cargo_unit_fingerprint(),
        ),
    ];
    settings.extend(BUILD_CONFIGURATION_OPTIONAL_ENV_KEYS.iter().map(|key| {
        (
            (*key).to_owned(),
            env::var(key).unwrap_or_else(|_| "<unset>".to_owned()),
        )
    }));
    settings.extend(env::vars().filter(|(key, _)| {
        key.starts_with("CARGO_CFG_")
            || key.starts_with("CARGO_FEATURE_")
            || key.starts_with("CARGO_PROFILE_")
    }));
    settings.sort();
    settings.dedup_by(|left, right| left.0 == right.0);

    let mut canonical = String::new();
    for (key, value) in settings {
        write!(canonical, "{}:{key}{}:{value}", key.len(), value.len())
            .expect("writing to String cannot fail");
    }
    sha256::digest_hex(canonical.as_bytes())
}

fn emit_build_configuration_env_watches() {
    for key in BUILD_CONFIGURATION_REQUIRED_ENV_KEYS
        .iter()
        .chain(BUILD_CONFIGURATION_OPTIONAL_ENV_KEYS)
    {
        println!("cargo:rerun-if-env-changed={key}");
    }
    let mut cargo_keys = env::vars()
        .map(|(key, _)| key)
        .filter(|key| {
            key.starts_with("CARGO_CFG_")
                || key.starts_with("CARGO_FEATURE_")
                || key.starts_with("CARGO_PROFILE_")
        })
        .collect::<Vec<_>>();
    cargo_keys.sort();
    cargo_keys.dedup();
    for key in cargo_keys {
        println!("cargo:rerun-if-env-changed={key}");
    }
}

fn cargo_unit_fingerprint() -> String {
    // Cargo does not expose every resolved profile setting to build scripts.
    // Its unit directory binds additional resolved settings without binding to
    // TARGET_DIR. build_info adds the target crate identity to the final hash.
    let out_dir = required_env("OUT_DIR");
    Path::new(&out_dir)
        .parent()
        .and_then(Path::file_name)
        .and_then(|name| name.to_str())
        .filter(|name| !name.is_empty())
        .unwrap_or_else(|| panic!("OUT_DIR does not contain a Cargo unit fingerprint: {out_dir:?}"))
        .to_owned()
}

fn emit_source_watches(manifest_dir: &Path) {
    let entries = fs::read_dir(manifest_dir)
        .unwrap_or_else(|error| panic!("could not enumerate package sources: {error}"));
    for entry in entries {
        let entry =
            entry.unwrap_or_else(|error| panic!("could not inspect package source: {error}"));
        let file_name = entry.file_name();
        if matches!(file_name.to_str(), Some(".git" | ".burner" | "target")) {
            continue;
        }
        println!("cargo:rerun-if-changed={}", entry.path().display());
    }
}

fn required_env(name: &str) -> String {
    let value = env::var(name).unwrap_or_else(|_| panic!("{name} is required"));
    if value.trim().is_empty() || value.contains('\n') || value.contains('\r') {
        panic!("{name} is empty or contains a newline");
    }
    value
}

fn emit(name: &str, value: &str) {
    if value.is_empty() || value.contains('\n') || value.contains('\r') {
        panic!("build attestation value {name} is empty or contains a newline");
    }
    println!("cargo:rustc-env={name}={value}");
}

fn command_output(directory: &Path, program: &str, arguments: &[&str]) -> String {
    let output = Command::new(program)
        .args(arguments)
        .current_dir(directory)
        .output()
        .unwrap_or_else(|error| panic!("could not run {program}: {error}"));
    if !output.status.success() {
        panic!(
            "{program} {} failed with {}: {}",
            arguments.join(" "),
            output.status,
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }
    String::from_utf8(output.stdout)
        .unwrap_or_else(|error| panic!("{program} output was not UTF-8: {error}"))
        .trim()
        .to_owned()
}
